#!/bin/bash
set -e

# Initialize configs
if command -v openvpn3-admin >/dev/null; then
    sudo openvpn3-admin init-config --write-configs || true
fi

# Reload dbus
systemctl reload dbus || true

exit 0
