#!/bin/bash
set -e

# Create group if not exists
if ! getent group openvpn >/dev/null; then
    groupadd -r openvpn
fi

# Create user if not exists
if ! id -u openvpn >/dev/null 2>&1; then
    useradd -r -s /usr/sbin/nologin -g openvpn openvpn
fi


exit 0
