name: Build Mac Dpkg

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  package-mac:
    strategy:
      matrix:
        include:
          # --------------------
          # macOS
          # --------------------
          - name: macOS arm64 14
            runner: macos-14

          - name: macOS arm64 15
            runner: macos-15

          - name: macOS arm64 26
            runner: macos-26

          - name: macOS amd64 15
            runner: macos-15-intel

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:

    - name: Checkout packaging repo
      uses: actions/checkout@v4

    - name: Download GUI artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: AaryaTalgaonkar/openvpn3-gui
        workflow: mac-build.yml
        branch: main
        name: OpenVPN3-GUI-${{ matrix.name }}
        path: mac/gui
        
    - name: Download Backend artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: AaryaTalgaonkar/openvpn3
        workflow: mac-build.yml
        branch: master
        name: backend-build-${{matrix.name}}
        path: mac/openvpn3

    - name: Install WiX
      shell: powershell
      run: |
        dotnet tool install --global wix
        echo "$env:USERPROFILE\.dotnet\tools" | Out-File -Append -Encoding ascii $env:GITHUB_PATH
    
    - name: Build MSI
      shell: powershell
      run: |
            cd windows
            wix build Product.wxs Gui.wxs `
              -arch ${{matrix.arch}} `
              -o IITDelhiVPN-${{matrix.arch}}.msi

    - name: Upload MSI
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: IITDelhiVPN-${{matrix.arch}}
        path: windows/IITDelhiVPN-${{matrix.arch}}.msi

    - name: Upload deb to Release
      if: github.event_name != 'workflow_dispatch'
      uses: softprops/action-gh-release@v2
      with:
        files: windows/IITDelhiVPN-${{matrix.arch}}.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
