name: Build Mac .pkg

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  package-mac:
    strategy:
      matrix:
        include:
          # --------------------
          # macOS
          # --------------------
          - name: macOS-arm64-14
            runner: macos-14

          - name: macOS-arm64-15
            runner: macos-15

          - name: macOS-arm64-26
            runner: macos-26

          - name: macOS-amd64-15
            runner: macos-15-intel

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:

    - name: Checkout packaging repo
      uses: actions/checkout@v4

    - name: Download GUI artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: AaryaTalgaonkar/openvpn3-gui
        workflow: mac-build.yml
        branch: main
        name: OpenVPN3-GUI-${{ matrix.name }}
        path: gui-artifact

    - name: Extract GUI
      run: |
        mkdir -p mac/pkgroot/Applications
        tar -xvf gui-artifact/OpenVPN3-GUI-${{ matrix.name }}.tar -C mac/pkgroot/Applications

        
    - name: Download Backend artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: AaryaTalgaonkar/openvpn3
        workflow: mac-build.yml
        branch: master
        name: backend-build-${{ matrix.name }}
        path: backend-artifact
    
    - name: Extract backend
      run: |
        mkdir backend-extract
        tar -xvf backend-artifact/backend-build-${{ matrix.name }}.tar -C backend-extract
    
        mkdir -p mac/pkgroot/Applications/app.app/Contents/openvpn3
        mv backend-extract/omicliagent mac/pkgroot/Applications/app.app/Contents/openvpn3/
    
        mkdir -p mac/pkgroot/Library/PrivilegedHelperTools
        mv backend-extract/agent_macos mac/pkgroot/Library/PrivilegedHelperTools/

    - name: Print pkgroot directory structure
      run: |
        echo "=== PKGROOT DIRECTORY STRUCTURE ==="
        find mac -print | sed 's|^|/|'

    - name: Build pkg
      run: |
        cd mac
        pkgbuild --root pkgroot --scripts scripts --identifier org.openvpn.agent --version 1.0 --install-location / openvpn3-${{ matrix.name }}.pkg

    # - name: Upload .pkg
    #   if: github.event_name == 'workflow_dispatch'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: IITDelhiVPN-${{ matrix.name }}
    #     path: mac/app.app

    # - name: Upload .pkg to Release
    #   if: github.event_name != 'workflow_dispatch'
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: windows/IITDelhiVPN-${{matrix.arch}}.msi
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
